### ISSUE TITLE
[Bug] Visualis proxy user does not have permission to read dataset when executing widget

### ISSUE THREAD

**Issue by utopianet** [apache/incubator-linkis#3254]
### Search before asking

- [X] I searched the [issues](https://github.com/apache/incubator-linkis/issues) and found no similar issues.

### Linkis Component

linkis-commons

### Steps to reproduce

Visualis uses the proxy user to execute the widget without permission to read the dataset
1、使用管理员用户创建工作空间，并添加非实名用户，以及实名用户adm，并赋予相应权限。
2、使用非实名用户创建项目、工作流，并拖拽SQL、WIDGET组件。
3、工作流设置使用代理用户adm执行。
4、WIDGET执行失败，提示用户hadoop无读取SQL数据集权限。

### Expected behavior

![Snipaste_2022-09-06_09-09-05](https://user-images.githubusercontent.com/6178793/188527027-a2b57c79-38d7-4624-bf98-70f3d3a82066.png)
[visualis.zip](https://github.com/apache/incubator-linkis/files/9492603/visualis.zip)

### Your environment

- Linkis version used: 1.1.1
- Environment name and version:
    - cdh-5.16.1
    - hive-1.1.0
    - spark-2.4.4
    - jdk 1.8.0_121

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

**Comment by peacewong** [comment]
![image](https://user-images.githubusercontent.com/11496700/188541984-682f7991-a805-4af3-8d10-902eeeefcc91.png)
When getting the result set, you should pass in the fs of the correct user so that there will be no permission problem, in `com.webank.wedatasphere.dss.visualis.entrance.spark.LinkisClientExecutor.getResultSet`
